export const products = [
    {
        id: 1,
        name: 'Apple',
        price: 3,
        description: 'Fresh and crispy apples.',
        image: 'https://via.placeholder.com/400?text=Apple',
        company: 'Fresh Farm',
        rating: 4.5,
        reviews: [
            { id: 1, rating: 5, text: 'Fantastic apples! Very fresh.' },
            { id: 2, rating: 4, text: 'Good quality, but slightly expensive.' },
        ],
    },
    {
        id: 2,
        name: 'Banana',
        price: 1,
        description: 'Sweet and ripe bananas.',
        image: 'https://via.placeholder.com/400?text=Banana',
        company: 'Banana Corp',
        rating: 4.2,
        reviews: [
            { id: 1, rating: 4, text: 'Tasty bananas, good value for money.' },
            { id: 2, rating: 3, text: 'A bit overripe, but still good.' },
        ],
    },
    {
        id: 3,
        name: 'Carrot',
        price: 2,
        description: 'Organic and fresh carrots.',
        image: 'https://via.placeholder.com/400?text=Carrot',
        company: 'Green Veggies',
        rating: 4.8,
        reviews: [
            { id: 1, rating: 5, text: 'Best carrots I have ever had!' },
            { id: 2, rating: 4, text: 'Very fresh and crunchy.' },
        ],
    },
    {
        id: 4,
        name: 'Broccoli',
        price: 4,
        description: 'Healthy green broccoli.',
        image: 'https://via.placeholder.com/400?text=Broccoli',
        company: 'Healthy Eats',
        rating: 4.7,
        reviews: [
            { id: 1, rating: 5, text: 'Perfect for a healthy diet.' },
            { id: 2, rating: 4, text: 'Fresh but a bit expensive.' },
        ],
    },
    {
        id: 5,
        name: 'Tomato',
        price: 2,
        description: 'Fresh red tomatoes.',
        image: 'https://via.placeholder.com/400?text=Tomato',
        company: 'Tomato Delight',
        rating: 4.3,
        reviews: [
            { id: 1, rating: 4, text: 'Juicy and fresh tomatoes.' },
            { id: 2, rating: 3, text: 'Some were too ripe.' },
        ],
    },
    {
        id: 6,
        name: 'Cucumber',
        price: 1,
        description: 'Cool and refreshing cucumbers.',
        image: 'https://via.placeholder.com/400?text=Cucumber',
        company: 'Fresh Harvest',
        rating: 4.6,
        reviews: [
            { id: 1, rating: 5, text: 'Crisp and refreshing, perfect for salads.' },
        ],
    },
    {
        id: 7,
        name: 'Strawberry',
        price: 3,
        description: 'Juicy red strawberries.',
        image: 'https://via.placeholder.com/400?text=Strawberry',
        company: 'Berry Land',
        rating: 4.9,
        reviews: [
            { id: 1, rating: 5, text: 'Sweetest strawberries I’ve had this season!' },
            { id: 2, rating: 5, text: 'Great quality and value.' },
        ],
    },
    {
        id: 8,
        name: 'Grapes',
        price: 5,
        description: 'Sweet and seedless grapes.',
        image: 'https://via.placeholder.com/400?text=Grapes',
        company: 'Vineyard Fresh',
        rating: 4.8,
        reviews: [
            { id: 1, rating: 5, text: 'Very sweet and juicy grapes.' },
            { id: 2, rating: 4, text: 'Good quality, but slightly expensive.' },
        ],
    },
    {
        id: 9,
        name: 'Mango',
        price: 6,
        description: 'Tropical golden mangoes.',
        image: 'https://via.placeholder.com/400?text=Mango',
        company: 'Tropical Fruits Co.',
        rating: 4.7,
        reviews: [
            { id: 1, rating: 5, text: 'Absolutely delicious mangoes!' },
            { id: 2, rating: 4, text: 'Fresh and flavorful.' },
        ],
    },
    {
        id: 10,
        name: 'Peach',
        price: 4,
        description: 'Soft and sweet peaches.',
        image: 'https://via.placeholder.com/400?text=Peach',
        company: 'Peach Paradise',
        rating: 4.5,
        reviews: [
            { id: 1, rating: 5, text: 'Perfectly ripe peaches.' },
            { id: 2, rating: 4, text: 'Sweet but a bit small in size.' },
        ],
    },
    {
        id: 11,
        name: 'Pineapple',
        price: 5,
        description: 'Fresh and tangy pineapple.',
        image: 'https://via.placeholder.com/400?text=Pineapple',
        company: 'Tropical Fruits Co.',
        rating: 4.6,
        reviews: [
            { id: 1, rating: 5, text: 'Amazing taste and quality.' },
        ],
    },
    {
        id: 12,
        name: 'Watermelon',
        price: 7,
        description: 'Refreshing watermelon slices.',
        image: 'https://via.placeholder.com/400?text=Watermelon',
        company: 'Summer Melons',
        rating: 4.4,
        reviews: [
            { id: 1, rating: 4, text: 'Sweet and refreshing.' },
        ],
    },
    {
        id: 13,
        name: 'Orange',
        price: 3,
        description: 'Juicy and tangy oranges.',
        image: 'https://via.placeholder.com/400?text=Orange',
        company: 'Citrus Farms',
        rating: 4.3,
        reviews: [
            { id: 1, rating: 4, text: 'Great for juicing!' },
        ],
    },
    {
        id: 14,
        name: 'Kiwi',
        price: 2,
        description: 'Tart and sweet kiwis.',
        image: 'https://via.placeholder.com/400?text=Kiwi',
        company: 'Exotic Fruits Co.',
        rating: 4.5,
        reviews: [
            { id: 1, rating: 5, text: 'Very juicy and tasty.' },
        ],
    },
    {
        id: 15,
        name: 'Blueberry',
        price: 4,
        description: 'Antioxidant-rich blueberries.',
        image: 'https://via.placeholder.com/400?text=Blueberry',
        company: 'Berry Land',
        rating: 4.9,
        reviews: [
            { id: 1, rating: 5, text: 'Best blueberries I’ve ever had!' },
        ],
    },
];
